local_backend: false

backend:
  name: github
  repo: michellrq25/still-weld-app # Repositorio de GitHub
  branch: main
  base_url: https://still-weld-app.vercel.app
  auth_endpoint: api/oauth

media_folder: "public/images/products"
public_folder: "/images/products"

collections:
  - name: "products_config"
    label: "Configuración"
    delete: false
    editor:
      preview: false
    files:
      - label: "Catálogo de Productos"
        name: "products_list"
        file: "public/products.json"
        fields:
          - label: "Productos"
            name: "products"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "ID", name: "id", widget: "number", value_type: "int" }
              - { label: "Nombre", name: "name", widget: "string" }
              - { label: "Imagen", name: "image", widget: "image", required: false }
